services:
  backend:
    build:
      context: ./backend-clone-shopee
      dockerfile: Dockerfile
    container_name: backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopee_clone?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      URL_FRONTEND: https://shop.khongkhoangcach.com
      VNPAY_RETURN_URL: https://shop.khongkhoangcach.com/api/v1/vnpay/return
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./reactjs-clone-shopee
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: http://backend:8080
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8081:80"

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopee_clone
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      # ✅ Lưu dữ liệu thật trên VPS (ngoài container)
      - /var/www/fullstack-shopee-clone/mysql_data:/var/lib/mysql
    restart: unless-stopped
