spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/shopee_clone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

URL_FONTENT: http://localhost:5173

app:
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8080/api/v1/vnpay/return
    tmn-code: X69NK85M
    secret-key: R8TBKWA3Q10F2RCRWGRZHT6205124ZMS
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
