spring:
  application:
    name: shopee
  mvc:
    trailing-slash-match: true
  profiles:
    active: dev # default chạy dev khi local

# Config upload file chung
file:
  upload:
    dir: uploads

# URL frontend (override trong từng profile nếu cần)
URL_FONTENT: http://localhost:5173

# JWT config (có fallback nếu không truyền ENV)
minh:
  jwt:
    access-token:
      secret: hxd9VMgxBcNfQaxRp+cqsPNWobWR+ZGC5HjN7daezaZLooCp8xBanW+siQ12wGkGscH+a3iHVfbds21jt/qtkA==
      validity: 3600
    refresh-token:
      secret: hxd9VMgxBcNfQaxRp+cqsPNWobWR+ZGC5HjN7daezaZLooCp8xBanW+siQ12wGkGscH+a3iHVfbds21jt/qtkA==
      validity: 604800
  cloudinary:
    cloud_name: dwjqosrrk
    api_key: 391995177417558
    api_secret: AYhNLy8Ol7umHf_9p00s_kJTnw8
app:
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8080/api/v1/vnpay/return
    tmn-code: X69NK85M
    secret-key: HT8EQ8SLUE0S3CXXHOCXT8U0A2NRWO74
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
