spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

URL_FONTENT: ${URL_FRONTEND:http://localhost:5173}

app:
  vnpay:
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8080/api/v1/vnpay/return
    tmn-code: X69NK85M
    secret-key: R8TBKWA3Q10F2RCRWGRZHT6205124ZMS
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
