spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://160.250.65.242:3306/shopee_clone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

URL_FRONTEND: http://localhost:5173
